version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - goconst
          - lll
        path: cmd/*
      - linters:
          - dupl
          - goconst
          - gocyclo
          - lll
        path: cmd/exp/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - gocyclo
        path: internal/exp/simplestreams/index/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lxc/cluster-api-provider-incus)
        - dot
    goimports:
      local-prefixes:
        - github.com/lxc/cluster-api-provider-incus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
